// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['app']['App']['AddConnection'](arg1);
}

export function ClearQueryHistory() {
  return window['go']['app']['App']['ClearQueryHistory']();
}

export function ConfirmCard(arg1) {
  return window['go']['app']['App']['ConfirmCard'](arg1);
}

export function ConfirmToolCall(arg1, arg2) {
  return window['go']['app']['App']['ConfirmToolCall'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function CreateConversation(arg1) {
  return window['go']['app']['App']['CreateConversation'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['app']['App']['DeleteConversation'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExecuteQueryWithLimit(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteQueryWithLimit'](arg1, arg2, arg3);
}

export function FormatQuery(arg1, arg2) {
  return window['go']['app']['App']['FormatQuery'](arg1, arg2);
}

export function GetAIConfig() {
  return window['go']['app']['App']['GetAIConfig']();
}

export function GetConnection(arg1) {
  return window['go']['app']['App']['GetConnection'](arg1);
}

export function GetConnectionStatus(arg1) {
  return window['go']['app']['App']['GetConnectionStatus'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['app']['App']['GetConversation'](arg1);
}

export function GetConversationHistory(arg1) {
  return window['go']['app']['App']['GetConversationHistory'](arg1);
}

export function GetDatabaseInfo(arg1) {
  return window['go']['app']['App']['GetDatabaseInfo'](arg1);
}

export function GetDatabases(arg1) {
  return window['go']['app']['App']['GetDatabases'](arg1);
}

export function GetQueryHistory(arg1, arg2) {
  return window['go']['app']['App']['GetQueryHistory'](arg1, arg2);
}

export function GetQueryHistoryByDBType(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetQueryHistoryByDBType'](arg1, arg2, arg3);
}

export function GetQueryHistoryStats() {
  return window['go']['app']['App']['GetQueryHistoryStats']();
}

export function GetSupportedDatabaseTypes() {
  return window['go']['app']['App']['GetSupportedDatabaseTypes']();
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTableInfo(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableInfo'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['app']['App']['GetTables'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ListConnections() {
  return window['go']['app']['App']['ListConnections']();
}

export function ListConversations() {
  return window['go']['app']['App']['ListConversations']();
}

export function RejectCard(arg1) {
  return window['go']['app']['App']['RejectCard'](arg1);
}

export function RetryQuery(arg1) {
  return window['go']['app']['App']['RetryQuery'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageWithEvents(arg1, arg2) {
  return window['go']['app']['App']['SendMessageWithEvents'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function UpdateAIConfig(arg1) {
  return window['go']['app']['App']['UpdateAIConfig'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['app']['App']['UpdateConnection'](arg1);
}

export function UpdateConversation(arg1) {
  return window['go']['app']['App']['UpdateConversation'](arg1);
}

export function ValidateQuery(arg1, arg2) {
  return window['go']['app']['App']['ValidateQuery'](arg1, arg2);
}
