// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExecuteQueryWithLimit(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQueryWithLimit'](arg1, arg2, arg3);
}

export function FormatQuery(arg1, arg2) {
  return window['go']['main']['App']['FormatQuery'](arg1, arg2);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetConnectionStatus(arg1) {
  return window['go']['main']['App']['GetConnectionStatus'](arg1);
}

export function GetDatabaseInfo(arg1) {
  return window['go']['main']['App']['GetDatabaseInfo'](arg1);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetSupportedDatabaseTypes() {
  return window['go']['main']['App']['GetSupportedDatabaseTypes']();
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTableInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableInfo'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function ValidateQuery(arg1, arg2) {
  return window['go']['main']['App']['ValidateQuery'](arg1, arg2);
}
