// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddConnection(arg1:Record<string, any>):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<database.QueryResult>;

export function ExecuteQueryWithLimit(arg1:string,arg2:string,arg3:number):Promise<database.QueryResult>;

export function FormatQuery(arg1:string,arg2:string):Promise<string>;

export function GetConnection(arg1:string):Promise<database.ConnectionConfig>;

export function GetConnectionStatus(arg1:string):Promise<database.ConnectionStatus>;

export function GetDatabaseInfo(arg1:string):Promise<database.DatabaseInfo>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetSupportedDatabaseTypes():Promise<Array<string>>;

export function GetTableData(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<database.QueryResult>;

export function GetTableInfo(arg1:string,arg2:string,arg3:string):Promise<database.TableInfo>;

export function GetTables(arg1:string,arg2:string):Promise<Array<database.TableInfo>>;

export function Greet(arg1:string):Promise<string>;

export function ListConnections():Promise<Array<database.ConnectionConfig>>;

export function TestConnection(arg1:Record<string, any>):Promise<void>;

export function UpdateConnection(arg1:Record<string, any>):Promise<void>;

export function ValidateQuery(arg1:string,arg2:string):Promise<void>;
